name: Bash Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck on all bash scripts
        run: |
          # Run shellcheck and generate output in GCC format, so it can be parsed as annotations
          find . -name "*.sh" -print0 | xargs -0 shellcheck --format=gcc
          
        continue-on-error: false
